version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:19-git
    environment:
      #DOCKER_TLS_CERTDIR: ''
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Docker build.
          command: docker build -t gcr.io/golang-demo:$CIRCLE_BRANCH .
      - run:
          name: Running Unit tests.
          command: echo 'running Unit tests...'
      - run:
          name: Pushing to Sonar.
          command: echo 'pushing to Sonar...'
  test:
    # working_directory: /app
    docker:
      - image: docker:19-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Running Acceptance tests.
          command: echo 'running Acceptance tests...'
      - run:
          name: Running Performance tests.
          command: echo 'running Performance tests...'
      - run:
          name: Running Security tests.
          command: echo 'running Security tests...'
  deploy-development:
    working_directory: /app
    docker:
      - image: docker:19-git
    steps:
      - run:
          name: Deploy to development env.
          command: echo 'Deploy to development env...'
  deploy-staging:
    working_directory: /app
    docker:
      - image: docker:19-git
    steps:
      - run:
          name: Deploy to staging env.
          command: echo 'Deploy to staging env...'
  deploy-prod:
    working_directory: /app
    docker:
      - image: docker:19-git
    steps:
      - run:
          name: Deploy to prod env
          command: echo 'Deploy to prod env...'
workflows:
  version: 2
  build-and-deploy-on-hold:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - staging
                - /feature*/
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy-development:
          requires:
            - test
            - build
          filters:
            branches:
              only: /feature*/
      - deploy-staging:
          requires:
            - test
            - build
          filters:
            branches:
              only: staging
      - deploy-prod:
          requires:
            - build
            - test
            - hold
          filters:
            branches:
              only: master
# workflows:
#   version: 2
#   dev_stage_pre-prod:
#     jobs:
#       - test_dev:
#           filters:  # using regex filters requires the entire branch to match
#             branches:
#               only:  # only branches matching the below regex filters will run
#                 - dev
#                 - development
#                 - /feature*/
#       - test_stage:
#           filters:
#             branches:
#               only: stage
#       - test_pre-prod:
#           filters:
#             branches:
#               only: /pre-prod(?:-.+)?$/

      # - setup_remote_docker:
      #     docker_layer_caching: true
#   test:
#     docker:
#       - image: docker:stable-git
#     steps:
#       - checkout
#       - run: echo 'testing here...'
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test


# version: 2.0
# jobs:
#   untagged-build:
#     jobs:
#       - build
#   tagged-build:
#     jobs:
#       - build:
#           filters:
#             tags:
#               only: /^v.*/
#   test:
#     steps:
#       - run: echo "Testting..."


# version: 2.0
# jobs:
#   check-and-build-only:
#     executor: docker
#     steps:
#       - checkout
#       - docker/check
#       - docker/build:
#           image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build:
#           filters:
#             branches:
#               ignore:

#                 - develop
#                 - /feature-.*/
#       - test:
#       - deploy-stage:
#           requires:
#             - build
#           filters:
#             branches:
#               only: staging
#       - deploy-prod:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
#             tags:
#               only: /v.*/

# version: 2.1
# orbs:
#   docker: circleci/docker@0.5.13
#   gcp-gke: circleci/gcp-gke@0.1.0
#   gcr: circleci/gcp-gcr@0.0.2
# jobs:
#   build:
#     description: Docker Build
#     # machine option runs your jobs in a dedicated, ephemeral VM that has the following specifications:
#     machine: true
#     steps:
#       - checkout
#       # Install node
#       - node/install
#       # Install npm
#       - node/install-npm
#       # Download and cache dependencies
#       - node/with-cache:
#           steps:
#             - run:
#                 name: Install application dependencies
#                 command: npm install
#           # Save cache
#           cache-key: package.json
#           # Ignore non-checksum cache hits
#           use-strict-cache: true
#   Build-Push-Image-Docker:
#     description: Build and push image to Google Container Registry
#     machine: true
#     steps:
#       - checkout
#       - gcr/gcr-auth
#       - gcr/build-image:
#           image: circle-gke
#           tag: "v2" #Change version number e.g to 'v3' when updating application
#       - gcr/push-image:
#           image: circle-gke
#           tag: "v2" #Change version number e.g to 'v3' when updating application
#
#   deploy:
#     description: Deploy application to Google Kubernetes Engine
#     machine: true
#     steps:
#       # Install `gcloud` and `kubectl` if not already installed.
#       - gcp-gke/install
#       # Initialize the `gcloud` CLI.
#       - gcp-gke/init
#       # Update a deployment Docker image.
#       - gcp-gke/rollout-image:
#           deployment: circle-ci-cluster
#           container: dominic-backend
#           image: gcr.io/circle-ci-demo/circle-gke:v2 # change version when updating
# workflows:
#   build_update_deploy:
#     jobs:
#       - build
#       - Build-Push-Image-Docker:
#           requires:
#             - build
#       - deploy:
#           requires:
#             - Build-Push-Image-Docker
